import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// The one-shot UI cues. Files live in `assets/sounds/` and are generated by
/// `tool/generate_sounds.py`.
enum Sfx {
  tap('tap.wav'),
  correct('correct.wav'),
  incorrect('incorrect.wav'),
  complete('complete.wav'),
  post('post.wav'),
  celebrate('celebrate.wav');

  const Sfx(this.file);
  final String file;
}

/// Plays short interaction sounds.
///
/// Two rules keep it from getting annoying: a small pool of players so cues can
/// overlap without cutting each other off mid-note, and a per-cue debounce so a
/// fast double tap doesn't stack the same sample on top of itself.
class SoundService {
  SoundService();

  static const _poolSize = 4;
  final List<AudioPlayer> _pool = [];
  int _next = 0;
  bool _ready = false;
  final Map<Sfx, DateTime> _lastPlayed = {};

  static const _debounce = Duration(milliseconds: 70);

  /// Master mute, driven by the user's setting.
  bool enabled = true;

  Future<void> init() async {
    if (_ready) return;
    try {
      AudioPlayer.global.setAudioContext(
        AudioContextConfig(
          // Never grab audio focus: lesson video audio must keep playing.
          focus: AudioContextConfigFocus.mixWithOthers,
          route: AudioContextConfigRoute.system,
        ).build(),
      );
      for (var i = 0; i < _poolSize; i++) {
        final player = AudioPlayer()..setReleaseMode(ReleaseMode.stop);
        await player.setVolume(0.55);
        _pool.add(player);
      }
      _ready = true;
    } catch (e) {
      // Audio is a nice-to-have: a device that refuses to give us players
      // shouldn't take the app down with it.
      debugPrint('SoundService init failed: $e');
    }
  }

  void play(Sfx sfx, {double volume = 0.55}) {
    if (!enabled || !_ready) return;
    final now = DateTime.now();
    final last = _lastPlayed[sfx];
    if (last != null && now.difference(last) < _debounce) return;
    _lastPlayed[sfx] = now;

    final player = _pool[_next];
    _next = (_next + 1) % _pool.length;
    unawaited(_fire(player, sfx, volume));
  }

  Future<void> _fire(AudioPlayer player, Sfx sfx, double volume) async {
    try {
      await player.stop();
      await player.setVolume(volume);
      await player.play(AssetSource('sounds/${sfx.file}'));
    } catch (e) {
      debugPrint('SoundService play(${sfx.name}) failed: $e');
    }
  }

  Future<void> dispose() async {
    for (final p in _pool) {
      await p.dispose();
    }
    _pool.clear();
    _ready = false;
  }
}
