import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

/// One-shot confetti burst layered over the results screen.
///
/// The Lottie file is generated by `tool/generate_lottie.py` — each particle is
/// a shape layer whose position keyframes sample a projectile trajectory, so the
/// burst arcs and falls instead of fanning out in straight lines.
class ConfettiBurst extends StatefulWidget {
  const ConfettiBurst({super.key, this.onFinished});

  final VoidCallback? onFinished;

  @override
  State<ConfettiBurst> createState() => _ConfettiBurstState();
}

class _ConfettiBurstState extends State<ConfettiBurst>
    with SingleTickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(vsync: this);

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return IgnorePointer(
      child: Lottie.asset(
        'assets/lottie/confetti.json',
        controller: _controller,
        fit: BoxFit.cover,
        repeat: false,
        onLoaded: (composition) {
          _controller
            ..duration = composition.duration
            ..forward().whenComplete(() => widget.onFinished?.call());
        },
        // If the asset can't be decoded there's simply no confetti; the screen
        // behind it still works.
        errorBuilder: (_, __, ___) => const SizedBox.shrink(),
      ),
    );
  }
}

/// Wraps [child] and lets any descendant fire a confetti burst over it.
class CelebrationScope extends StatefulWidget {
  const CelebrationScope({super.key, required this.child, this.autoPlay = false});

  final Widget child;
  final bool autoPlay;

  @override
  State<CelebrationScope> createState() => CelebrationScopeState();

  static CelebrationScopeState? maybeOf(BuildContext context) =>
      context.findAncestorStateOfType<CelebrationScopeState>();
}

class CelebrationScopeState extends State<CelebrationScope> {
  int _burst = 0;
  bool _playing = false;

  void celebrate() {
    if (!mounted) return;
    setState(() {
      _burst++;
      _playing = true;
    });
  }

  @override
  void initState() {
    super.initState();
    if (widget.autoPlay) {
      WidgetsBinding.instance.addPostFrameCallback((_) => celebrate());
    }
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        widget.child,
        if (_playing)
          Positioned.fill(
            child: ConfettiBurst(
              key: ValueKey(_burst),
              onFinished: () {
                if (mounted) setState(() => _playing = false);
              },
            ),
          ),
      ],
    );
  }
}
